apiVersion: v1
data:
  API_HOST: 0.0.0.0
  API_PORT: "3000"
  MONGO_HOST: mongo
  MONGO_INITDB_DATABASE: mydatabase
  MONGO_INITDB_ROOT_PASSWORD: password
  MONGO_INITDB_ROOT_USERNAME: root
  MONGO_PORT: "27017"
  NODE_ENV: development
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: api-dev-env
  name: dev-env
